# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7692599e9bd52ae5191089474f818c6d59781d63e581d0a74cc039b5017acaf7fec70a58b0a44939e5c3215ec112478d9bbc96ccdf16b48b61e055763e9c041

test:
  secret_key_base: 7e186377edbeef4f1fe918cfb155a29b1564d1cb734f73d678b7ec5392d63ad597ad0f97ecdc5b21516affe0fc398fd324ed363c671d5e0f5c10383512b6dacf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
